- id: test_push_pullMode
  sourceEvent: push
  pullMode: true
  triggered: true
- id: test_regex
  sourceEvent: issue_comment
  number: 4
  prefixFilter: '$gofunky([-\/]bot)?'
  commandFilter: ''
  appendCommand: false
  pullMode: false
  body: |
    $gofunky my test trigger
    Something else
  triggered: true
  command: my test trigger
- id: test_regex_nocommand
  sourceEvent: issue_comment
  number: 4
  prefixFilter: '$gofunky([-\/]bot)?'
  commandFilter: ''
  appendCommand: false
  pullMode: false
  body: |
    $gofunky/bot
    Something else
  triggered: true
  command: ''
- id: test_regex_notrigger
  sourceEvent: issue_comment
  number: 4
  prefixFilter: '$gofunky([-\/]bot)?'
  commandFilter: ''
  appendCommand: false
  pullMode: false
  body: |
    $gofunk-bot foo
    Something else
  triggered: false
  command: ''
- id: test_no_affiliation_notrigger
  sourceEvent: issue_comment
  number: 1
  prefixFilter: '$gofunky([-\/]bot)?'
  commandFilter: ''
  appendCommand: false
  pullMode: false
  body: |
    $gofunky my test trigger
    Something else
  triggered: false
  command: my test trigger
- id: test_empty_prefix
  sourceEvent: issue_comment
  number: 4
  prefixFilter: ''
  commandFilter: ''
  appendCommand: false
  pullMode: false
  body: |
    Something irrelevant
  triggered: true
  command: ''
- id: test_empty_body
  sourceEvent: issue_comment
  number: 4
  prefixFilter: ''
  commandFilter: ''
  appendCommand: false
  pullMode: false
  body: ''
  triggered: true
  command: ''
