name: automatic review

on:
  pull_request_target:
    branches:
      - master
    types:
      - review_requested

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: check for automatic approval
        uses: golfzaptw/action-auto-reviews-from-branches@1.2.1
        with:
          GITHUB_TOKEN: ${{ secrets.BOT }}
          EVENT_TYPE: APPROVE
          AUTHOR: 'dependabot-preview[bot], dependabot[bot], renovate[bot], gofunky-bot, matfax'
          MESSAGE: This pull request has automatically been approved.
