name: autosquash

on:
  check_run:
    types:
      - completed
  pull_request_target:
    types:
      - closed
      - labeled
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: tibdex/autosquash@v2.1.0
        with:
          github_token: ${{ secrets.BOT }}
