name: codeowners

on:
  pull_request_target:
    paths-ignore:
      - '**/CODEOWNERS'
      - 'LICENSE'
    branches:
      - master
    types:
      - ready_for_review
      - review_request_removed
      - reopened
      - labeled

jobs:
  update:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged_by == ''
    steps:
      - name: checkout code
        uses: actions/checkout@v2.3.2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.BOT }}
      - name: update code owners
        uses: gofunky/update-codeowners@v0.3.1
        with:
          distribution: 25
          username: true
      - name: commit changed files
        id: committed
        uses: stefanzweifel/git-auto-commit-action@v4.5.1
        with:
          commit_message: 'chore(meta): update code owners'
          file_pattern: .github/CODEOWNERS
      - uses: christianvuerings/add-labels@v1.1
        if: ${{ steps.committed.outputs.changes_detected == 'true' }}
        with:
          labels: owned
        env:
          GITHUB_TOKEN: ${{ secrets.BOT }}
