name: observe

on:
  workflow_run:
    workflows:
      - 'test'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2.3.2
        with:
          persist-credentials: false
      - name: execute observer
        uses: ./observer/
