name: merge

on:
  pull_request_target:
    branches:
      - master
    types:
      - opened
  issue_comment:
    types:
      - created
  pull_request_review:
    types:
      - submitted

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: add reaction
        uses: khan/pull-request-comment-trigger@1.0.0
        id: check
        with:
          trigger: 'LGTM'
          reaction: rocket
        env:
          GITHUB_TOKEN: ${{ secrets.BOT }}
      - name: checkout code
        if: steps.check.outputs.triggered == 'true'
        uses: actions/checkout@v2.3.2
      - name: check if merge was approved by code owner
        if: steps.check.outputs.triggered == 'true'
        uses: orta/code-owner-self-merge@1.4.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
