name: revert

on:
  issue_comment:
    types:
      - created

jobs:
  commit:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/revert')
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT }}
      - name: automatically revert commit on request
        uses: srt32/revert@v0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.BOT }}
